name: Maven Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
      type: [opened, reopened, edited]

jobs:
  build:
    name: Build YDB Java SDK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots install
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  examples:
    name: Build and test Java SDK Examples
    runs-on: ubuntu-latest
    needs: build

    env:
        EXAMPLES_BRANCH: ${{ github.ref == 'refs/heads/master' && 'master' || 'develop' }}

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ydb-platform/ydb-java-examples
          ref: ${{env.EXAMPLES_BRANCH}}
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build examples with Maven
        run: mvn test
