name: YDB Java SDK CI with Maven

on:
  push:
    branches:
      - master
      - develop
  pull_request:
      type: [opened, reopened, edited]

jobs:
  build:
    name: Build YDB Java SDK
    runs-on: ubuntu-latest

    env:
        MAVEN_ARGS: --batch-mode --update-snapshots -Dstyle.color=always

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'

      - name: Download dependencies
        run: mvn $MAVEN_ARGS dependency:go-offline

      - name: Build with Maven
        run: mvn $MAVEN_ARGS install

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Store YDB Java SDK artifacts
        id: store-ydb-java-sdk
        uses: actions/upload-artifact@v3
        with:
          name: ydb-java-sdk.zip
          retention-days: 1
          path: ~/.m2/repository/tech/ydb

  yc-auth-provider:
    name: Build YC Auth Provider
    runs-on: ubuntu-latest
    needs: build

    env:
        MAVEN_ARGS: --batch-mode --update-snapshots -Dstyle.color=always
        YC_BRANCH: ${{ github.ref == 'refs/heads/master' && 'master' || 'develop' }}

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ydb-platform/ydb-java-yc
          ref: ${{env.YC_BRANCH}}

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cleanup tech.ydb artifacts
        run: rm -rf ~/.m2/repository/tech/ydb >/dev/null || true

      - name: Download built YDB Java SDK actifacts
        id: download-ydb-java-sdk
        uses: actions/download-artifact@v3
        with:
          path: ~/.m2/repository/tech/ydb/
          name: ydb-java-sdk.zip

#      - name: Download dependencies
#        run: mvn dependency:go-offline

      - name: Build YDB Java YC Auth privider
        run: mvn $MAVEN_ARGS install

      - name: Update YDB Java SDK artifacts
        id: update-ydb-java-sdk
        uses: actions/upload-artifact@v3
        with:
          name: ydb-java-sdk.zip
          retention-days: 1
          path: ~/.m2/repository/tech/ydb

  examples:
    name: Test Java SDK Examples
    runs-on: ubuntu-latest
    needs: yc-auth-provider

    env:
        MAVEN_ARGS: --batch-mode --update-snapshots -Dstyle.color=always
        EXAMPLES_BRANCH: ${{ github.ref == 'refs/heads/master' && 'master' || 'develop' }}

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ydb-platform/ydb-java-examples
          ref: ${{env.EXAMPLES_BRANCH}}

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cleanup tech.ydb artifacts
        run: rm -rf ~/.m2/repository/tech/ydb >/dev/null || true

      - name: Download built YDB Java SDK actifacts
        id: download-ydb-java-sdk
        uses: actions/download-artifact@v3
        with:
          path: ~/.m2/repository/tech/ydb/
          name: ydb-java-sdk.zip

#      - name: Download dependencies
#        run: mvn --batch-mode --update-snapshots dependency:go-offline

      - name: Test examples with Maven
        run: mvn $MAVEN_ARGS test
