name: Build&Test YDB Java SDK Examples

on:
  push:
    branches:
      - master
      - develop
  pull_request:
      type: [opened, reopened, edited]

jobs:
  examples:
    runs-on: ubuntu-latest

    env:
        TEST1: $${{ github.ref }}
        TEST2: $${{ github.ref == 'refs/heads/master' }}
        EXAMPLES_BRANCH: ${{ github.ref == 'refs/heads/master' && 'master' || 'develop' }}

    steps:
      - name: test 1
        run: echo "${GITHUB_REF} -> ${TEST1} ${TEST2} ${EXAMPLES_BRANCH}"

